name: CD - Deploy on WebLogic

on:
  workflow_run:
    workflows: ["CI - Build and Share Artifact"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, cd-runner]

    steps:
      - name: Run Ansible from shared directory
        run: |
          cd /Users/nikhil/shared-artifacts
          ansible-playbook deploy.yaml
